dubbo:
  application:
    name: provider-admin
  scan:
    base-packages: com.dcy.service.provideradmin.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dcy-cloud?nullNamePatternMatchesAll=true&useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  flyway:
    enabled: true
    baseline-on-migrate: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.dcy.service.apiadmin.model
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: null