spring:
  redis:
    host: 192.168.0.2
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-biz
          uri: lb://admin-biz
          predicates:
            - Path=/admin-biz/**
          filters:
            - StripPrefix=1
        - id: auth-biz
          uri: lb://auth-biz
          predicates:
            - Path=/auth-biz/**
          filters:
            - StripPrefix=1


#设置最大超时时间
ribbon:
  eager-load:
    enabled: true
  ServerListRefreshInterval: 10  #刷新服务列表源的间隔时间
  ReadTimeout: 90000
  ConnectTimeout: 90000
  OkToRetryOnAllOperations: true #对所有操作请求都进行重试
  MaxAutoRetries: 1 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1 #切换服务器实例的重试次数

ignored: |
  /**/actuator/** , /**/actuator/**/** ,
  /v2/api-docs/**, /swagger-ui.html, /swagger-resources/**, /webjars/** ,
  /**/v2/api-docs/**, /**/swagger-ui.html, /**/swagger-resources/**, /**/webjars/**,
  /**/favicon.ico,
  /auth-biz/oauth/**,/auth-biz/getUserInfo,/auth-biz/getOAuthDetails,
  /admin-biz/**
