spring:
  redis:
    host: 192.168.0.2
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-center
          uri: lb://admin-center
          predicates:
            - Path=/admin-center/**
          filters:
            - StripPrefix=1
        - id: auth-center
          uri: lb://auth-center
          predicates:
            - Path=/auth-center/**
          filters:
            - StripPrefix=1
        - id: file-center
          uri: lb://file-center
          predicates:
            - Path=/file-center/**
          filters:
            - StripPrefix=1


#设置ribbon饥渴模式
ribbon:
  eager-load:
    enabled: true
    clients: auth-center,admin-center,file-center,monitor-center
  ServerListRefreshInterval: 10  #刷新服务列表源的间隔时间

ignored: |
  /v2/api-docs/**, /swagger-ui.html, /swagger-resources/**, /webjars/** ,
  /**/v2/api-docs/**, /**/swagger-ui.html, /**/swagger-resources/**, /**/webjars/**,
  /**/favicon.ico,
  /file-center/**,
  /auth-center/oauth/**,/auth-center/getUserInfo,/auth-center/getOAuthDetails,
  /admin-center/dict/getDictListByType,/admin-center/dict/getDictTreeListByGroupType
