spring:
  redis:
    host: 192.168.0.2
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-biz
          uri: lb://admin-biz
          predicates:
            - Path=/admin-biz/**
          filters:
            - StripPrefix=1
        - id: auth-biz
          uri: lb://auth-biz
          predicates:
            - Path=/auth-biz/**
          filters:
            - StripPrefix=1


#设置ribbon饥渴模式
ribbon:
  eager-load:
    enabled: true
    clients: auth-biz,admin-biz

ignored: |
  /**/actuator/** , /**/actuator/**/** ,
  /v2/api-docs/**, /swagger-ui.html, /swagger-resources/**, /webjars/** ,
  /**/v2/api-docs/**, /**/swagger-ui.html, /**/swagger-resources/**, /**/webjars/**,
  /**/favicon.ico,
  /auth-biz/oauth/**,/auth-biz/getUserInfo,/auth-biz/getOAuthDetails,
  /admin-biz/**
