dubbo:
  application:
    name: provider-sms
  scan:
    base-packages: com.dcy.sms.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
dcy:
  boot:
    sms:
      access-key-id: xxxxxxxxxx
      access-key-secret: xxxxxxxxxx
      sign-name: 测试签名
      version: 2017-05-25
      region-id: cn-hangzhou